apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Target
metadata:
  name: my-cluster
  namespace: example
spec:
  type: landscaper.gardener.cloud/kubernetes-cluster
  secretRef: 
    name: cluster-access